# Generated by Django 3.1.5 on 2021-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixin',
            name='mae',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mixin',
            name='pae',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
