# Generated by Django 3.1.5 on 2021-02-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20210205_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixin',
            options={'verbose_name': 'Mixin', 'verbose_name_plural': 'Mixins'},
        ),
    ]
